### ISSUE TITLE
Unable to bypass on certain resources for domain

### ISSUE THREAD

**Issue by jkaberg** [clems4ever/authelia#333]
With the following config I'm still presented with an login window? I was under the presumption that if I was trying to access for instance `https://sub.domain.tld/path1/api/...` I would not need to authenticate? :smile: 

Small config snippet
```
access_control:
  default_policy: deny
  rules:
    - domain: 'sub.domain.tld'
      resources:
        - '^/path1/rpc.*$'
        - '^/path2/api.*$'
        - '^/path3/api.*$'
      policy: bypass

    - domain: '*.domain.tld'
      subject: 'group:admins'
      policy: two_factor
```

**Comment by clems4ever** [comment]
Hello @jkaberg, the path you provided in your example matches the second rule with police two_factor. So, AFAIC, the behavior you see is expected.

Please double check your config.

**Comment by jkaberg** [comment]
@clems4ever okay, so perhaps I've misunderstood the docs/example? How can I make the resources at sub.domain.tld (the api endpoints) available for anyone without auth regardless if they're authenticated or not?

**Comment by clems4ever** [comment]
Helo @jkaberg ,

**Comment by clems4ever** [comment]
Hello @jkaberg ,
```
access_control:
  default_policy: deny
  rules:
  - domain: 'sub.domain.tld'
    policy: bypass
```
should be enough for any resource from `sub.domain.tld` to be allowed to everyone.

In your first example you provided `/path1/api/...` which either matches your second rule if you're an admin or the default policy if you're not.

For the latest example you require, the following should be ok
```
access_control:
  default_policy: deny
  rules:
  - domain: 'sub.domain.tld'
    resources:
    - "^/path1/.*$"
    policy: bypass
```

**Comment by jkaberg** [comment]
Well that doesn't work @clems4ever, my config is exactly like what you mentioned and I'm still presented with the auth window. I guess this is a bug?

On another note, my impression when reading the following config is that (in this particular order):
- IF domain IS sub.domain.tld AND resource (path) IS x/y/z REQUIRE bypass (none)
- ELSE IF domain IS *.domain.tld AND "subject" (user/group) IS group:admins REQUIRE two_factor

Am I wrong in how I interpret this? I feel that the documentation is a bit lacking in this regard.
```
access_control:
  default_policy: deny
  rules:
    - domain: 'sub.domain.tld'
      resources:
        - '^/path1/rpc.*$'
        - '^/path2/api.*$'
        - '^/path3/api.*$'
      policy: bypass

    - domain: '*.domain.tld'
      subject: 'group:admins'
      policy: two_factor
```

**Comment by clems4ever** [comment]
Hello @jkaberg , the interpretation you give is indeed correct. If you've already done a bit of iptables config, it's the same idea. Basically, the first matching rule applies and default_policy is the policy to be applied if there is no match at all.
I will try your first example in a suite to see if I can reproduce.

**Comment by clems4ever** [comment]
@jkaberg , do you have some logs?

**Comment by clems4ever** [comment]
Well, there is indeed a bug. I can reproduce it. I'm working on it.

**Comment by clems4ever** [comment]
#336 should fix the issue.

**Comment by jkaberg** [comment]
@clems4ever Nice find! I will try this asap it lands in the master branch (and thus the Docker container you build from that)

**Comment by clems4ever** [comment]
It's merged, it will reach Dockerhub in few minutes.

**Comment by jkaberg** [comment]
@clems4ever Ok so tried it now, with the same config as my first post I'm still presented with login window on https://sub.domain.tld/path1/rpc/...

However if I set default_policy to bypass, it will not present login window for any resource as the config sits now (notice the *.domain.tld rule with group:admins and two_factor, this one is never enforced now)

**Comment by clems4ever** [comment]
Hello @jkaberg, do you have some logs ?
I will also add more logs in the rules matching system to improve debugging of this kind of issue.

**Comment by nightah** [comment]
@jkaberg I've also tried to re-produce this issue with no success.

Below is my configuration:
```
access_control:
  # Default policy can either be `bypass`, `one_factor`, `two_factor` or `deny`.
  # It is the policy applied to any resource if there is no policy to be applied
  # to the user.
  default_policy: deny

  rules:
    # Rules applied to everyone
    - domain: auth.example.com
      policy: bypass

    # Rules for bypassing
    - domain: '*.example.com'
      resources:
        - '^/api/.*$'
      policy: bypass

    # Rules applied to group 'Grafana Admins'
    - domain: '*.example.com'
      subject: 'group:Grafana Admins'
      policy: two_factor
```

If I hit anything under the `/api/` URI this is successfully returned however if I hit any domain on `*.example.com` for example `grafana.example.com` at a root level or any URI other than `/api/` it forwards to Authelia for authentication.

Could you confirm are you running the `latest` tagged docker container or `master`?
If the former, that's going to be your problem, could you please attempt with `master`.

**Comment by jkaberg** [comment]
@clems4ever @nightah With the following config running `master` I still get redirected to the login page

```
access_control:
  default_policy: deny
  rules:
    - domain: auth.example.tld
      policy: bypass

    - domain: sub.example.tld
      resources:
        - '^/path1/rpc/.*$'
        - '^/path3/api/.*$'
        - '^/path2/api/.*$'
      policy: bypass

    - domain: '*.example.tld'
      subject: 'group:admins'
      policy: two_factor

    - domain: dev.example.tld
      subject: 'user:user1'
      policy: two_factor

    - domain: test.example.tld
      subject: 'user:user2'
      policy: two_factor
```
The following is generated when I visit `https://sub.example.tld/path2/api/test`
```
auth_1_68b91072604c | info: date='Thu Mar 28 2019 11:20:57 GMT+0100 (CET)' message='Starting Authelia...'
auth_1_68b91072604c | info: date='Thu Mar 28 2019 11:20:57 GMT+0100 (CET)' message='Listening on port 80...'
auth_1_68b91072604c | debug: date='Thu Mar 28 2019 11:21:07 GMT+0100 (CET)' method='GET', path='/api/verify' requestId='d16eb02c-b12d-4f6c-8fb6-918b54ccc818' sessionId='bNFT8sL4K4dHPp7IpGYoSDDGyWGs_lwc' ip='192.168.1.128' message='Headers = {"host":"auth","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.5","cookie":"authelia_session=s%3AbNFT8sL4K4dHPp7IpGYoSDDGyWGs_lwc.%2BfOCas1AUrDXXLxpTRSnoiKHIgw%2F5uk2bnOK0ORvK74","dnt":"1","upgrade-insecure-requests":"1","x-forwarded-for":"192.168.1.128","x-forwarded-host":"sub.example.tld","x-forwarded-method":"GET","x-forwarded-proto":"https","x-forwarded-uri":"/path2/api/test","x-original-url":"https://sub.example.tld/path2"}'
auth_1_68b91072604c | debug: date='Thu Mar 28 2019 11:21:07 GMT+0100 (CET)' method='GET', path='/api/verify' requestId='d16eb02c-b12d-4f6c-8fb6-918b54ccc818' sessionId='bNFT8sL4K4dHPp7IpGYoSDDGyWGs_lwc' ip='192.168.1.128' message='Header x-original-url is set to https://sub.example.tld/path2'
auth_1_68b91072604c | debug: date='Thu Mar 28 2019 11:21:07 GMT+0100 (CET)' method='GET', path='/api/verify' requestId='d16eb02c-b12d-4f6c-8fb6-918b54ccc818' sessionId='bNFT8sL4K4dHPp7IpGYoSDDGyWGs_lwc' ip='192.168.1.128' message='Header x-original-url is set to https://sub.example.tld/path2'
auth_1_68b91072604c | debug: date='Thu Mar 28 2019 11:21:07 GMT+0100 (CET)' method='GET', path='/api/verify' requestId='d16eb02c-b12d-4f6c-8fb6-918b54ccc818' sessionId='bNFT8sL4K4dHPp7IpGYoSDDGyWGs_lwc' ip='192.168.1.128' message='domain=sub.example.tld, path=/path2, user=unknown, groups=unknown'
auth_1_68b91072604c | error: date='Thu Mar 28 2019 11:21:07 GMT+0100 (CET)' method='GET', path='/api/verify' requestId='d16eb02c-b12d-4f6c-8fb6-918b54ccc818' sessionId='bNFT8sL4K4dHPp7IpGYoSDDGyWGs_lwc' ip='192.168.1.128' message='Error: User 'unknown' is not sufficiently authorized to access sub.example.tld/path2.'
auth_1_68b91072604c | debug: date='Thu Mar 28 2019 11:21:07 GMT+0100 (CET)' method='GET', path='/api/verify' requestId='d16eb02c-b12d-4f6c-8fb6-918b54ccc818' sessionId='bNFT8sL4K4dHPp7IpGYoSDDGyWGs_lwc' ip='192.168.1.128' message='Redirecting to https://auth.example.tld?rd=https://sub.example.tld/path2'
auth_1_68b91072604c | debug: date='Thu Mar 28 2019 11:21:07 GMT+0100 (CET)' method='GET', path='/api/state' requestId='64df4849-962f-4583-9ce1-55ff0ad378af' sessionId='bNFT8sL4K4dHPp7IpGYoSDDGyWGs_lwc' ip='192.168.1.128' message='Headers = {"host":"auth.example.tld","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","accept":"*/*","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.5","cookie":"authelia_session=s%3AbNFT8sL4K4dHPp7IpGYoSDDGyWGs_lwc.%2BfOCas1AUrDXXLxpTRSnoiKHIgw%2F5uk2bnOK0ORvK74","dnt":"1","if-none-match":"W/\"4b-s/Hr08v2qZgerJUP/NGltuHVbcU\"","referer":"https://auth.example.tld/?rd=https://sub.example.tld/path2","te":"trailers","x-forwarded-for":"192.168.1.128","x-forwarded-host":"auth.example.tld","x-forwarded-port":"443","x-forwarded-proto":"https","x-forwarded-server":"b684f584470a","x-real-ip":"192.168.1.128"}'
```

**Comment by jkaberg** [comment]
Perhaps this is due to me running Authelia with Traefik as suggested [here](https://github.com/clems4ever/authelia/issues/88#issuecomment-473344850)?

**Comment by clems4ever** [comment]
Hello @jkaberg , Authelia is indeed using the x-original-url and does not reconstruct the URL from the set of headers you mention. @nightah and I will help you by providing a version of Authelia building the URL if X-Original-URL is not provided unless you want to do it yourself.

**Comment by nightah** [comment]
@jkaberg I'm reading the traefik documentation and I can see where you can construct custom headers, but I can't see if you can reference existing headers while attempting to construct custom ones. Is this possible?

**Comment by ViViDboarder** [comment]
@clems4ever I've got a version doing that in a branch that @jkaberg referenced. I'm happy to submit it as a PR.

**Comment by nightah** [comment]
@ViViDboarder, perhaps you might have some insight on my above question. Do you know if this is possible with traefik?

**Comment by ViViDboarder** [comment]
@nightah as far as I know, you cannot.

**Comment by jkaberg** [comment]
👍 will try when @ViViDboarder PR is in master

**Comment by jkaberg** [comment]
So with https://github.com/clems4ever/authelia/commit/4016ff1bbaf6a1fd76ce51e49d8559bed3477315 in use everything works as expected. Thanks again @clems4ever !
